
Creating model.....
Creating training dataset...
Creating valid dataset...






Val_loss 0.07309 | Valid_accuracy_value 0.00000 | Valid_accuracy_average 0.00000uracy_average 0.01691
Traceback (most recent call last):
  File "main.py", line 196, in <module>
    train(args)
  File "main.py", line 156, in train
    wandb.log({"Table": show_img_wandb(img, hm_gt, pred_logit)})
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1339, in log
    self.history._row_add(data)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_history.py", line 44, in _row_add
    self._flush()
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1018, in _history_callback
    row, step, publish_step=not_using_tensorboard
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 496, in publish_history
    data = data_types.history_dict_to_json(run, data, step=step)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/wandb/sdk/data_types.py", line 2597, in history_dict_to_json
    payload[key] = val_to_json(run, key, val, namespace=step)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/wandb/sdk/data_types.py", line 2670, in val_to_json
    run.log_artifact(art)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 2486, in log_artifact
    return self._log_artifact(artifact_or_path, name, type, aliases)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 2619, in _log_artifact
    self._assert_can_log_artifact(artifact)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 2668, in _assert_can_log_artifact
    public_api.settings["project"],
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/wandb/apis/public.py", line 3586, in expected_type
    "name": name,
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 159, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/wandb/apis/public.py", line 205, in execute
    return self._client.execute(*args, **kwargs)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/home/junshick/anaconda3/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/home/junshick/anaconda3/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/home/junshick/anaconda3/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/junshick/anaconda3/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 325, in recv_into
    if not util.wait_for_read(self.socket, self.socket.gettimeout()):
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/urllib3/util/wait.py", line 146, in wait_for_read
    return wait_for_socket(sock, read=True, timeout=timeout)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/urllib3/util/wait.py", line 107, in poll_wait_for_socket
    return bool(_retry_on_intr(do_poll, timeout))
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/urllib3/util/wait.py", line 43, in _retry_on_intr
    return fn(timeout)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/urllib3/util/wait.py", line 105, in do_poll
    return poll_obj.poll(t)
KeyboardInterrupt