2022-03-04 10:35:33,155 INFO    MainThread:669511 [wandb_setup.py:_flush():71] setting env: {}
2022-03-04 10:35:33,155 INFO    MainThread:669511 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-04 10:35:33,155 INFO    MainThread:669511 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-04 10:35:33,155 INFO    MainThread:669511 [wandb_init.py:_log_setup():371] Logging user logs to /home/junshick/Workspace/pose_estimation/custom_pose/wandb/run-20220304_103533-31npbn0s/logs/debug.log
2022-03-04 10:35:33,155 INFO    MainThread:669511 [wandb_init.py:_log_setup():372] Logging internal logs to /home/junshick/Workspace/pose_estimation/custom_pose/wandb/run-20220304_103533-31npbn0s/logs/debug-internal.log
2022-03-04 10:35:33,155 INFO    MainThread:669511 [wandb_init.py:init():404] calling init triggers
2022-03-04 10:35:33,155 INFO    MainThread:669511 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-03-04 10:35:33,155 INFO    MainThread:669511 [wandb_init.py:init():460] starting backend
2022-03-04 10:35:33,155 INFO    MainThread:669511 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-04 10:35:33,162 INFO    MainThread:669511 [backend.py:ensure_launched():216] starting backend process...
2022-03-04 10:35:33,165 INFO    MainThread:669511 [backend.py:ensure_launched():222] started backend process with pid: 669520
2022-03-04 10:35:33,167 INFO    MainThread:669511 [wandb_init.py:init():469] backend started and connected
2022-03-04 10:35:33,168 INFO    MainThread:669511 [wandb_init.py:init():533] updated telemetry
2022-03-04 10:35:33,179 INFO    MainThread:669511 [wandb_init.py:init():563] communicating current version
2022-03-04 10:35:33,629 INFO    MainThread:669511 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-04 10:35:33,629 INFO    MainThread:669511 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-03-04 10:35:33,912 INFO    MainThread:669511 [wandb_init.py:init():606] starting run threads in backend
2022-03-04 10:35:36,547 INFO    MainThread:669511 [wandb_run.py:_console_start():1810] atexit reg
2022-03-04 10:35:36,547 INFO    MainThread:669511 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-03-04 10:35:36,548 INFO    MainThread:669511 [wandb_run.py:_redirect():1689] Redirecting console.
2022-03-04 10:35:36,549 INFO    MainThread:669511 [wandb_run.py:_redirect():1745] Redirects installed.
2022-03-04 10:35:36,549 INFO    MainThread:669511 [wandb_init.py:init():633] run started, returning control to user process
2022-03-04 10:35:38,708 INFO    MainThread:669511 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-03-04 10:35:38,709 INFO    MainThread:669511 [wandb_run.py:_restore():1752] restore
2022-03-04 10:35:41,061 INFO    MainThread:669511 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2022-03-04 10:35:41,403 INFO    MainThread:669511 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2022-03-04 10:35:41,921 INFO    MainThread:669511 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 5939
}

2022-03-04 10:35:42,023 INFO    MainThread:669511 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 15538
}

2022-03-04 10:35:42,126 INFO    MainThread:669511 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 15538
}

2022-03-04 10:35:42,227 INFO    MainThread:669511 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 15538
}

2022-03-04 10:35:42,329 INFO    MainThread:669511 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15538
  total_bytes: 15538
}

2022-03-04 10:35:42,432 INFO    MainThread:669511 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15538
  total_bytes: 15538
}

2022-03-04 10:35:42,534 INFO    MainThread:669511 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15538
  total_bytes: 15538
}

2022-03-04 10:35:42,637 INFO    MainThread:669511 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15538
  total_bytes: 15538
}

2022-03-04 10:35:42,739 INFO    MainThread:669511 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15538
  total_bytes: 15538
}

2022-03-04 10:35:42,842 INFO    MainThread:669511 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15538
  total_bytes: 15538
}

2022-03-04 10:35:43,154 INFO    MainThread:669511 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15538
  total_bytes: 15538
}

2022-03-04 10:35:43,703 INFO    MainThread:669511 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15538
  total_bytes: 15538
}
local_info {
}

2022-03-04 10:35:44,768 INFO    MainThread:669511 [wandb_run.py:_append_files():2180] logging synced files
