Creating model.....
Creating training dataset...
Creating valid dataset...
train_loader length: 94
valid_loader length: 32




Epoch [0][83/94] | Train_loss 0.08070
Traceback (most recent call last):
  File "main.py", line 170, in <module>
    train(args)
  File "main.py", line 130, in train
    wandb.log({"Table": show_img_wandb(img, hm_gt, pred_logit)})
  File "/home/junshick/Workspace/pose_estimation/custom_pose/utils/wandb_img.py", line 25, in show_img_wandb
    table = wandb.Table(data=my_data, columns = ["Image", "Ground Truth", "Prediction"])
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/wandb/data_types.py", line 246, in __init__
    self._init_from_list(data, columns, optional, dtype)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/wandb/data_types.py", line 273, in _init_from_list
    self.add_data(*row)
  File "/home/junshick/anaconda3/lib/python3.7/site-packages/wandb/data_types.py", line 420, in add_data
    len(self.columns), self.columns, len(data)

Epoch [0][93/94] | Train_loss 0.08238