2022-03-06 13:01:28,959 INFO    MainThread:697578 [wandb_setup.py:_flush():71] setting env: {}
2022-03-06 13:01:28,959 INFO    MainThread:697578 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-06 13:01:28,959 INFO    MainThread:697578 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-06 13:01:28,959 INFO    MainThread:697578 [wandb_init.py:_log_setup():371] Logging user logs to /home/junshick/Workspace/pose_estimation/custom_pose/wandb/run-20220306_130128-12nytxhq/logs/debug.log
2022-03-06 13:01:28,959 INFO    MainThread:697578 [wandb_init.py:_log_setup():372] Logging internal logs to /home/junshick/Workspace/pose_estimation/custom_pose/wandb/run-20220306_130128-12nytxhq/logs/debug-internal.log
2022-03-06 13:01:28,960 INFO    MainThread:697578 [wandb_init.py:init():404] calling init triggers
2022-03-06 13:01:28,960 INFO    MainThread:697578 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-03-06 13:01:28,960 INFO    MainThread:697578 [wandb_init.py:init():460] starting backend
2022-03-06 13:01:28,960 INFO    MainThread:697578 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-06 13:01:28,967 INFO    MainThread:697578 [backend.py:ensure_launched():216] starting backend process...
2022-03-06 13:01:28,972 INFO    MainThread:697578 [backend.py:ensure_launched():222] started backend process with pid: 697587
2022-03-06 13:01:28,972 INFO    MainThread:697578 [wandb_init.py:init():469] backend started and connected
2022-03-06 13:01:28,973 INFO    MainThread:697578 [wandb_init.py:init():533] updated telemetry
2022-03-06 13:01:28,985 INFO    MainThread:697578 [wandb_init.py:init():563] communicating current version
2022-03-06 13:01:30,000 INFO    MainThread:697578 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-06 13:01:30,000 INFO    MainThread:697578 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-03-06 13:01:30,299 INFO    MainThread:697578 [wandb_init.py:init():606] starting run threads in backend
2022-03-06 13:01:32,851 INFO    MainThread:697578 [wandb_run.py:_console_start():1810] atexit reg
2022-03-06 13:01:32,851 INFO    MainThread:697578 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-03-06 13:01:32,851 INFO    MainThread:697578 [wandb_run.py:_redirect():1689] Redirecting console.
2022-03-06 13:01:32,853 INFO    MainThread:697578 [wandb_run.py:_redirect():1745] Redirects installed.
2022-03-06 13:01:32,853 INFO    MainThread:697578 [wandb_init.py:init():633] run started, returning control to user process
2022-03-06 13:01:35,071 INFO    MainThread:697578 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-03-06 13:01:35,072 INFO    MainThread:697578 [wandb_run.py:_restore():1752] restore
2022-03-06 13:01:37,865 INFO    MainThread:697578 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2022-03-06 13:01:38,122 INFO    MainThread:697578 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2022-03-06 13:01:38,306 INFO    MainThread:697578 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2022-03-06 13:01:38,407 INFO    MainThread:697578 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 15674
}

2022-03-06 13:01:38,510 INFO    MainThread:697578 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 15674
}

2022-03-06 13:01:38,612 INFO    MainThread:697578 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 15674
}

2022-03-06 13:01:38,713 INFO    MainThread:697578 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15674
  total_bytes: 15674
}

2022-03-06 13:01:38,815 INFO    MainThread:697578 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15674
  total_bytes: 15674
}

2022-03-06 13:01:38,917 INFO    MainThread:697578 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15674
  total_bytes: 15674
}

2022-03-06 13:01:39,020 INFO    MainThread:697578 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15674
  total_bytes: 15674
}

2022-03-06 13:01:39,122 INFO    MainThread:697578 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15674
  total_bytes: 15674
}

2022-03-06 13:01:39,224 INFO    MainThread:697578 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15674
  total_bytes: 15674
}

2022-03-06 13:01:39,534 INFO    MainThread:697578 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15674
  total_bytes: 15674
}

2022-03-06 13:01:40,189 INFO    MainThread:697578 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15674
  total_bytes: 15674
}
local_info {
}

2022-03-06 13:01:41,258 INFO    MainThread:697578 [wandb_run.py:_append_files():2180] logging synced files
