2022-03-06 12:00:53,514 INFO    MainThread:696091 [wandb_setup.py:_flush():71] setting env: {}
2022-03-06 12:00:53,514 INFO    MainThread:696091 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-06 12:00:53,514 INFO    MainThread:696091 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-06 12:00:53,514 INFO    MainThread:696091 [wandb_init.py:_log_setup():371] Logging user logs to /home/junshick/Workspace/pose_estimation/custom_pose/wandb/run-20220306_120053-h5brqvp7/logs/debug.log
2022-03-06 12:00:53,514 INFO    MainThread:696091 [wandb_init.py:_log_setup():372] Logging internal logs to /home/junshick/Workspace/pose_estimation/custom_pose/wandb/run-20220306_120053-h5brqvp7/logs/debug-internal.log
2022-03-06 12:00:53,514 INFO    MainThread:696091 [wandb_init.py:init():404] calling init triggers
2022-03-06 12:00:53,514 INFO    MainThread:696091 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-03-06 12:00:53,514 INFO    MainThread:696091 [wandb_init.py:init():460] starting backend
2022-03-06 12:00:53,515 INFO    MainThread:696091 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-06 12:00:53,521 INFO    MainThread:696091 [backend.py:ensure_launched():216] starting backend process...
2022-03-06 12:00:53,525 INFO    MainThread:696091 [backend.py:ensure_launched():222] started backend process with pid: 696100
2022-03-06 12:00:53,526 INFO    MainThread:696091 [wandb_init.py:init():469] backend started and connected
2022-03-06 12:00:53,527 INFO    MainThread:696091 [wandb_init.py:init():533] updated telemetry
2022-03-06 12:00:53,539 INFO    MainThread:696091 [wandb_init.py:init():563] communicating current version
2022-03-06 12:00:54,545 INFO    MainThread:696091 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-06 12:00:54,545 INFO    MainThread:696091 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-03-06 12:00:55,128 INFO    MainThread:696091 [wandb_init.py:init():606] starting run threads in backend
2022-03-06 12:00:57,712 INFO    MainThread:696091 [wandb_run.py:_console_start():1810] atexit reg
2022-03-06 12:00:57,712 INFO    MainThread:696091 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-03-06 12:00:57,712 INFO    MainThread:696091 [wandb_run.py:_redirect():1689] Redirecting console.
2022-03-06 12:00:57,713 INFO    MainThread:696091 [wandb_run.py:_redirect():1745] Redirects installed.
2022-03-06 12:00:57,713 INFO    MainThread:696091 [wandb_init.py:init():633] run started, returning control to user process
2022-03-06 12:00:59,971 INFO    MainThread:696091 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-03-06 12:00:59,972 INFO    MainThread:696091 [wandb_run.py:_restore():1752] restore
2022-03-06 12:01:02,725 INFO    MainThread:696091 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2022-03-06 12:01:02,827 INFO    MainThread:696091 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2022-03-06 12:01:03,271 INFO    MainThread:696091 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 766
}

2022-03-06 12:01:04,138 INFO    MainThread:696091 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 63291
}

2022-03-06 12:01:04,240 INFO    MainThread:696091 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 63291
}

2022-03-06 12:01:04,342 INFO    MainThread:696091 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 63291
}

2022-03-06 12:01:04,444 INFO    MainThread:696091 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 766
  total_bytes: 63291
}

2022-03-06 12:01:04,547 INFO    MainThread:696091 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 63291
  total_bytes: 63291
}

2022-03-06 12:01:04,649 INFO    MainThread:696091 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 63291
  total_bytes: 63291
}

2022-03-06 12:01:04,751 INFO    MainThread:696091 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 63291
  total_bytes: 63291
}

2022-03-06 12:01:04,853 INFO    MainThread:696091 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 63291
  total_bytes: 63291
}

2022-03-06 12:01:04,955 INFO    MainThread:696091 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 63291
  total_bytes: 63291
}

2022-03-06 12:01:05,423 INFO    MainThread:696091 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 63291
  total_bytes: 63291
}

2022-03-06 12:01:06,038 INFO    MainThread:696091 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 63291
  total_bytes: 63291
}
local_info {
}

2022-03-06 12:01:07,105 INFO    MainThread:696091 [wandb_run.py:_append_files():2180] logging synced files
